ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.fakescreen.pro
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.dev.fakescreen.pro
      paths:
        - path: /
          pathType: ImplementationSpecific
