apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fakescreen-frontend.fullname" . }}
  labels:
    {{- include "fakescreen-frontend.labels" . | nindent 4 }}
spec:
  secretName: {{ printf "%s-tls" .Chart.Name }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
    {{- end }}
